#!/bin/bash

topdir="$(cd "$(dirname "$0")" && pwd -P)"

case "${OSTYPE:-}" in
    darwin*)
        if command -v gcp >/dev/null 2>&1; then
            copy () {
                gcp -al "$@"
            }
        else
            copy () {
                cp -a "$@"
            }
        fi
        ;;
    *)
        copy () {
            cp -al "$@"
        }
esac

git init
copy "$topdir"/.git/objects/. .git/objects/
git remote add origin "$topdir"
git fetch --tags origin
git fetch origin
git remote set-url origin "$(cd "$topdir" && git config remote.origin.url)"
git fetch origin || :
git checkout -f -b master origin/master

cp "$topdir/.envrc" .
./script/init
cp -a "$topdir/Library/library.db" Library/
cp -a "$topdir/"*_token.json .

sed -i.bak -e '/^ *# - nowrite/s/# //' config.yaml
rm -f config.yaml.bak

direnv allow

if [ "${VISUAL:-${EDITOR:-vim}}" = code ]; then
    code .
fi
