#!/bin/bash

topdir="$(cd "$(dirname "$0")/.." && pwd -P)"

case "${OSTYPE:-}" in
    darwin*)
        if command -v gcp >/dev/null 2>&1; then
            copy () {
                gcp -al "$@"
            }
        else
            copy () {
                cp -a "$@"
            }
        fi
        ;;
    *)
        copy () {
            cp -al "$@"
        }
esac

git init
copy "$topdir"/.git/objects/. .git/objects/
git remote add origin "$topdir"
git fetch --tags origin
git fetch origin
git remote set-url origin "$(cd "$topdir" && git config remote.origin.url)"
git fetch origin || :
git checkout -f -b main origin/main

cp -a "$topdir/"*.nix "$topdir/nix" .
for i in .envrc scripts config.yaml config.d hooks plugins; do
    cp -av "$topdir/$i" .
done
sed -i.bak -e '/^ *# - nowrite/s/# //' config.yaml
rm -f config.yaml.bak
cp -a "$topdir/"*_token.json .
mkdir -p Library
cp -a "$topdir/Library/library.db" Library/
cp -a "$topdir/Library/Playlists/." Library/Playlists/
../script/init

direnv allow

if [ "${VISUAL:-${EDITOR:-vim}}" = code ]; then
    code .
fi
