#!/bin/sh

topdir="${topdir:-$PWD/..}"
case "$OSTYPE" in
    darwin*)
        if command -v gcp >/dev/null 2>&1; then
            copy () {
                gcp -al "$@"
            }
        else
            copy () {
                cp -a "$@"
            }
        fi
        ;;
    *)
        copy () {
            cp -al "$@"
        }
esac

if [ ! -e "$topdir/Beets" ]; then
    topdir="${topdir%/*}"
    if [ ! -e "$topdir/Beets" ]; then
        echo >&2 "Error: unable to locate Beets folder, aborting"
        exit 1
    fi
fi

mkdir -p Beets
cd Beets || exit 1
git init
copy "$topdir"/Beets/.git/objects/. .git/objects/
git remote add origin "$topdir/Beets"
git fetch --tags origin
git fetch origin
git remote set-url origin "$(cd "$topdir/Beets" && git config remote.origin.url)"
git fetch origin || :
git checkout -f -b master origin/master
cd - >/dev/null || exit 1

cp "$topdir/.envrc" .
./Beets/script/init
cp -a "$topdir/Library/library.db" Library/
cp -a "$topdir/Beets/"*_token.json Beets/

sed -i.bak -e '/^ *# - nowrite/s/# //' Beets/config.yaml
rm -f Beets/config.yaml.bak

direnv allow

if [ "${VISUAL:-${EDITOR:-vim}}" = code ]; then
    code .
fi
