#!/bin/sh

id="$1"

if [ -n "$(beet ls id:"$id" artpath::'^$')" ]; then
    if beet get-config plugins | grep -q '\- hasart'; then
        if [ -n "$(beet ls id:"$id" has_embedded_art:true)" ]; then
            echo >&2 "Extracting embedded album art"
            beet extractart -a id:"$id"
        fi
    else
        echo >&2 "Extracting embedded album art if available"
        beet extractart -a id:"$id"
    fi
fi

if [ -n "$(beet ls -a id:"$id" comments::.)" ]; then
    echo >&2 "Exporting album comments to comments.txt in album folder"
    beet-export-album-comments id:"$id"
fi

echo >&2 "Generating par2 files"
beet -p musicintegrity par2create id:"$id" 2>/dev/null

beet ls -ap id:"$id"
