#!/bin/bash
# shellcheck disable=SC2016,SC2115

set -euo pipefail

msg() {
    printf >&2 "%s: %s\n" "$alternative" "$@"
}

scriptdir="$(cd "$(dirname "$0")" && pwd -P)"
# shellcheck source=common.sh
. "$scriptdir/common.sh"

alternative="$1"
directory="$2"

if [ -n "${BEETS_SKIP_HOOKS:-}" ]; then
    exit 0
fi

if config_true "alternatives.$alternative.playlists" true && config_true alternativesplaylist.auto true; then
    playlistdir="$(config_value 'alternativesplaylist.playlist_dir' || config_value 'playlist.playlist_dir' Playlists)"
    playlistdir="$(basename "$playlistdir")"
    if [ -n "$playlistdir" ]; then
        msg "Generating random single tracks playlist"
        mkdir -p "$directory/$playlistdir"
        beet random -f '$alt_'"$alternative" -n 999999999 ^alt_"$alternative":^ potential_single_track:true \
            | sed -e "s#^$directory/#../#" >"$directory/_Playlists/Random Single Tracks.m3u"
    fi
fi

msg "Converting symbolic links to relative"
find "$directory" -type l \
    | while read -r l; do
        if [ -e "$l" ]; then
            target="$(realpath "$l")"
            ln -fs "$(realpath --relative-to="$(dirname "$(realpath -s "$l")")" "$target")" "$l"
        fi
    done

if [ -z "${BEETS_ALT_SKIP_COVERS:-}" ]; then
    msg "Updating/converting covers"
    "$(dirname "$0")/../scripts/update-alternative-covers" "$alternative" "$directory"
fi

msg "Removing empty directories"
remove-empty-dirs "$directory"/*/ >/dev/null || :

if [ -d "$directory/.git" ]; then
    (
        cd "$directory" || exit 1
        git add -A .
        git commit -m "Update"
    )
fi
