#!/bin/bash
# shellcheck disable=SC2016,SC2115

set -euo pipefail

msg() {
    printf >&2 "%s: %s\n" "$alternative" "$@"
}

scriptdir="$(cd "$(dirname "$0")" && pwd -P)"
# shellcheck source=common.sh
. "$scriptdir/common.sh"

alternative="$1"
directory="$2"

if [ -n "${BEETS_SKIP_HOOKS:-}" ]; then
    exit 0
fi

if [ -z "${BEETS_ALT_SKIP_COVERS:-}" ]; then
    msg "Updating/converting covers"
    "$(dirname "$0")/../scripts/update-alternative-covers" "$alternative" "$directory"
fi

msg "Removing empty directories"
remove-empty-dirs "$directory"/*/ >/dev/null || :

if [ -d "$directory/.git" ]; then
    (
        cd "$directory" || exit 1
        git add -A .
        git commit -m "Update"
    )
fi
