#!/bin/sh
# shellcheck disable=SC2016,SC2115

set -e

msg() {
    printf >&2 "%s: %s\n" "$alternative" "$@"
}

alternative="$1"
directory="$2"

if [ -n "$BEETS_SKIP_HOOKS" ]; then
    exit 0
fi

playlistdir="$(beet get-config alternativesplaylist.playlist_dir)" || :
if [ "$playlistdir" = "null" ]; then
    playlistdir="$(beet get-config playlist.playlist_dir)" || :
    if [ "$playlistdir" = null ]; then
        playlistdir=Playlists
    else
        # FIXME: get a relative path to the library directory
        playlistdir="$(basename "$playlistdir")"
    fi
fi

if [ -d "$directory/$playlistdir" ]; then
    msg "Generating random single tracks playlist"
    beet random -f '$alt_'"$alternative" -n 999999999 alt_"$alternative":/Single\ Tracks/ \
        | sed -e "s#^$directory/#../#" >"$directory/_Playlists/Random Single Tracks.m3u"
fi

msg "Converting symbolic links to relative"
find "$directory" -type l \
    | while read -r l; do
        if [ -e "$l" ]; then
            target="$(realpath "$l")"
            ln -fs "$(realpath --relative-to="$(dirname "$(realpath -s "$l")")" "$target")" "$l"
        fi
    done

msg "Removing empty directories"
remove-empty-dirs "$directory"/*/ >/dev/null || :

if [ -z "$BEETS_ALT_SKIP_COVERS" ]; then
    msg "Updating/converting covers"
    "$(dirname "$0")/../scripts/update-alternative-covers" "$alternative" "$directory"
fi
