#!/bin/bash
# shellcheck disable=SC2016,SC2115

set -euo pipefail

msg() {
    printf >&2 "%s: %s\n" "$alternative" "$@"
}

scriptdir="$(cd "$(dirname "$0")" && pwd -P)"
# shellcheck source=common.sh
. "$scriptdir/common.sh"

alternative="$1"
directory="$2"

if [ -n "${BEETS_SKIP_HOOKS:-}" ]; then
    exit 0
fi

if [ -d "$directory" ]; then
    msg "Removing dead symlinks"
    find "$directory" -type l \
        | while read -r fn; do test -e "$fn" || echo "$fn"; done \
        | tr '\n' '\0' \
        | xargs -0 rm -fv \
        | sed -e 's,^,-,'
fi

if [ -d "$directory" ] || [ -z "${BEETS_ALT_SKIP_SPL:-}" ]; then
    if config_true "alternatives.$alternative.playlists" true && config_true alternativesplaylist.auto true; then
        if [ -z "${BEETS_ALT_SKIP_SPL:-}" ]; then
            msg "Updating smart playlists"
            beet splupdate
        fi
        if [ -d "$directory" ]; then
            playlistdir="$(config_value 'alternativesplaylist.playlist_dir' || config_value 'playlist.playlist_dir' Playlists)"
            playlistdir="$(basename "$playlistdir")"
            if [ -n "$playlistdir" ] && [ -d "$directory/$playlistdir" ]; then
                msg "Removing playlists for update"
                rm -rf "$directory/$playlistdir"
            fi
        fi
    fi
fi

msg Updating
