#!/bin/sh
# shellcheck disable=SC2016

if [ -n "$BEETS_SKIP_HOOKS" ]; then
    exit 0
fi

echo >&2 "Extracting any embedded album art if needed"
beet extractart -a last_import:1 "artpath:^" >/dev/null 2>&1

echo >&2 "Savings comments.txt if set"
beet-export-album-comments last_import:1

echo >&2 "Checking for red flags"
beet-check-sanity last_import:1

echo >&2 "Generating par2 files"
beet -p musicintegrity par2create last_import:1 2>/dev/null

beet ls -a -f '$path' last_import:1
beet ls -f '$path' last_import:1 singleton:true

has_open=0
if command -v xdg-open >/dev/null 2>&1; then
    has_open=1
elif command -v wsl-open >/dev/null 2>&1; then
    case "$(uname -r)" in
        *-Microsoft|*-microsoft-*)
            has_open=1
            ;;
    esac
fi

if [ -z "$BEETS_NO_REVEAL" ] && [ "$has_open" -eq 1 ]; then
    # Open the album folder
    beet open -- -a last_import:1

    # Reveal singleton files
    beet reveal last_import:1 singleton:true
fi
