#!/bin/sh
# Merge albums by ID, then re-import the merged album
# Note that we do not copy album metadata amongst the tracks the way
# `duplicates` does at this time, so this may need manual correction for
# merging non-musicbrainz albums if any key metadata mismatches.
#
# shellcheck disable=SC2046

set -eu

first_id="$1"
shift
echo >&2 "Merging album_ids $* into $first_id"
echo beet modify $(echo " $*" | sed -e 's/ / album_id:/g; s/^ //') "album_id=$first_id"
echo beet rm -a $(echo " $*" | sed -e 's/ / id:/g; s/^ //')
