#!/bin/bash
# Open or reveal the files from a `beet ls` query

set -euo pipefail

usage() {
    cat >&2 <<END
${0##*/} [options] [SEARCH_QUERY]

Options:

-R            Reveal
-A OPEN_ARGS  Specify arguments to pass along to the underlying open command.
-h            Show usage
END
exit 2
}

reveal=0
open_args=
while getopts RA:h opt; do
    case "$opt" in
        R)
            reveal=1
            ;;
        A)
            open_args="$OPTARG"
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

nlxargs () {
    tr '\n' '\0' | xargs -0 "$@"
}

# shellcheck disable=SC2039
case "${OSTYPE:-}" in
    darwin*)
        open=open
        ;;
    *)
        if command -v xdg-open >/dev/null 2>&1; then
            open=xdg-open
        elif command -v wsl-open >/dev/null 2>&1; then
            open=wsl-open
        else
            echo >&2 "Error: no xdg-open or wsl-open found"
            exit 1
        fi
        ;;
esac

tmpfile="$(mktemp -t "${0##*/}.XXXXXX")" || exit 1
trap 'rm -f "$tmpfile"' EXIT INT TERM

# shellcheck disable=SC2016
beet ls -p "$@" \
    | if [ "$reveal" -eq 1 ]; then
        nlxargs -n 1 dirname
    else
        cat
    fi \
    | awk '!visited[$0]++' >"$tmpfile"

if [ -s "$tmpfile" ]; then
    cat "$tmpfile" | ( eval set -- ${open_args:+$open_args}; nlxargs "$open" "$@"; )
fi
