#!/bin/sh
# Get info from acousticbrainz if available, otherwise submit to
# acousticbrainz for musicbrainz tracks and calculate and store what we can

set -e

beet abcalc
beet acousticbrainz
beet absubmit
