#!/bin/sh
# I really don't care about the mediafile/confuse deprecation warnings, make
# them go away with a wrapper script.

abs_script() {
    case "$script" in
        /*)
            echo "$0"
            ;;
        *)
            command -v "$0"
            ;;
    esac
}

run_wrapped() {
    (
        OIFS="$IFS"
        IFS=:
        for _path in $PATH; do
            if [ -x "$_path/beet" ] && [ -n "$(sed -ne '1{/python/p;}' "$_path/beet")" ]; then
                cd "$scriptdir/../.." && "$_path/beet" "$@"
                exit $?
            fi
        done
        echo >&2 "Error: 'beet' not found, please install beets."
        exit 1
    )
}

script="$(abs_script)"
scriptdir="$(dirname "$script")"

# Set up the pipe to filter out the messages I don't want without merging
# stdout and stderr
tmpdir="$(mktemp -d -t "${0##*/}.XXXXX")" || exit 1
trap 'rm -rf "$tmpdir"' EXIT INT TERM
errpipe="$tmpdir/errpipe"
mkfifo "$errpipe"

grep -Ev 'UserWarning|warnings.warn' <"$errpipe" >&2 &
run_wrapped "$@" 2>"$errpipe"
ret=$?
wait
exit "$ret"
