#!/bin/sh
# shellcheck disable=SC2016,SC2046

usage() {
    cat >&2 <<END
${0##*/} [options] [QUERY..]

Options:

  -n   Dry run.
  -s   Singletons, not albums.
  -S KEY=VALUE  Set a value on the imported album or singleton item regardless
                of reimport result.
END
exit 2
}

dry_run=0
album=1
set_values=
singleton=
while getopts nsS:h opt; do
    case "$opt" in
        n)
            dry_run=1
            ;;
        s)
            album=
            singleton=1
            ;;
        S)
            set_values="$set_values $OPTARG"
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

ret=0
tmp=$(mktemp -t "${0##*/}.XXXX")
trap 'rm -f "$tmp"' EXIT INT TERM

scriptdir="$(dirname "$0")"

beet ls ${album:+-a} -f '$id' ${singleton:+singleton:true} "$@" >"$tmp"
while read -r id; do
    id_query="${album:+album_}id:$id"
    if [ -n "$album" ]; then
        if [ $(beet ls -a -f '$source' "$id_query" | wc -l) -ne 1 ]; then
            echo >&2 "$id must have a single source set, skipping"
            continue
        fi
    fi

    beet ls ${album:+-a} "$id_query"

    printf >&2 '+ export "%s"\n' "$id_query"
    if [ $dry_run -eq 0 ]; then
        "$scriptdir/export" "$id_query"
    fi

    source="$(beet ls ${album:+-a} -f '$source' "$id_query")"
    printf >&2 '+ beet import -maL %s--set=source="%s" "%s"\n' "${singleton:+--singletons }" "$source" "$id_query"
    if [ $dry_run -eq 0 ]; then
        if ! beet import -maL ${singleton:+--singletons} --set=source="$source" "$id_query" </dev/tty; then
            ret=1
            break
        fi

        if [ -n "$set_values" ]; then
            # shellcheck disable=SC2086
            beet modify -y ${album:+-a} "$id_query" $set_values 2>/dev/null
            ret=$?
            if [ $ret -gt 127 ]; then
                # Exited due to signal
                exit $ret
            elif [ $ret -ne 0 ]; then
                # If the modify failed, the id changed, so the import must
                # have completed, and we can use last_import instead.
                # shellcheck disable=SC2086
                beet modify -y ${album:+-a} last_import:1 $set_values
            fi
        fi
    fi
done <"$tmp"
exit $ret
