#!/bin/sh

set -e

quote(){
    sed -e "s,','\\\\'',g; 1s,^,',; \$s,\$,',;" << EOF
$1
EOF
}

save () {
    case "$1" in
    # when a string contains a "'" we have to escape it
    *\'*)
        saved="$saved $(quote "$1")"
        ;;
    # otherwise just quote the variable
    *)
        saved="$saved '$1'"
        ;;
    esac
}

saved=
for i in $(seq 1 $#); do
    arg="$1"
    shift
    case "$arg" in
        -*)
            save "$arg"
            continue
            ;;
    esac
    set -- "$@" "$arg"
done

scriptdir="$(cd "$(dirname "$0")" && pwd -P)"

if [ $# -eq 0 ]; then
    set -- "$scriptdir/../By Source"/*/
fi

beet_import() {
    (
        for arg; do
            save "$arg"
        done
        eval set -- "$saved"
        command beet import "$@"
    )
}

for source; do
    source="${source%/}"
    case "$source" in
        */By\ Source/*)
            sourcename="${source##*/By Source/}"
            sourcename="${sourcename%%/*}"
            ;;
        *)
            sourcename=Unknown
            ;;
    esac
    echo >&2 "Importing $source"

    for non_album in "$source"/*/"[non-album tracks]"; do
        if [ -d "$non_album" ]; then
            beet_import -s --set=source="$sourcename" "$non_album"
            beet noimport "$non_album"
        fi
    done

    # Beets doesn't reliably pick up the compilation tag from much of my music
    # My guess is an interoperability issue with Picard.
    for comp in "$source/Compilations" "$source/Various Artists"; do
        if [ -d "$comp" ]; then
            beet_import --set=source="$sourcename" --set=comp=true "$comp"
        fi
    done

    beet_import --set=source="$sourcename" "$source"
done

beet modify -y -a albumartist::"^Various artists$" albumartist="Various Artists" || :
beet modify -y -a albumartist::"^Various$" albumartist="Various Artists" || :
beet modify -y "johannes aikio" genre=Game || :
beet modify -y "nacional records sampler" comp=true || :

# Fixup singletons
beet modify -y singleton:false album:"non-album tracks" album_id= album= || :
beet modify -y singleton:false album::"^$" album_id= album= || :
beet modify -y singleton:true album::"." album= || :

# Beets isn't picking up my manually set releasetype field for some reason
beet modify -y "You Don't Hear Jack" albumtype=spokenword || :
beet modify -y "Teachings on Love" albumtype=audiobook || :

# 'Various Artists' albums not flagged as compilations
beet modify -y -a is_various_no_comp:1 comp=true || :
