#!/usr/bin/env python3

from __future__ import division, absolute_import, print_function

from beets.library import Item
from beets import mediafile
from beets.plugins import BeetsPlugin

field = mediafile.MediaField(
    mediafile.MP3DescStorageStyle(u'ITUNESADVISORY'),
    mediafile.MP4StorageStyle(u'rtng'),
    mediafile.StorageStyle(u'ITUNESADVISORY'),
    mediafile.ASFStorageStyle(u'ITUNESADVISORY'),
    out_type=int,
)
plugin = BeetsPlugin()
plugin.add_media_field('itunesadvisory', field)

target = 'Library/Amazon/System of a Down/Mezmerize/07 - Violent Pornography.mp3'
mf = mediafile.MediaFile(target)
item = Item.from_path(mf.path)
print(item.title)
print(item.itunesadvisory)
