#!/bin/sh

dbfile="$(mktemp -t "${0##*/}.XXXXXX")" || exit 1
diskfile="$(mktemp -t "${0##*/}.XXXXXX")" || exit 1
trap 'rm -f "$dbfile" "$diskfile"' EXIT INT TERM

beet ls -f '$path' \
    | tr '[:upper:]' '[:lower:]' \
    | sort >"$dbfile"
sh -c '. ./scripts/common-music.sh && music_find "$PWD/Library"' \
    | tr '[:upper:]' '[:lower:]' \
    | sort >"$diskfile"
touch "$diskfile"
comm -13 "$dbfile" "$diskfile"
