#!/bin/sh
# If I've mucked up the source fields on my music,
# this uses a library backup to restore them
. scripts/common-music.sh

find_music () {
    fd -t d "$*" Old\ Library/ | while read -r f; do
        music_find "$f"
    done
}

fd -t d "$*" Library/Unknown
if [ $(fd -t d "$*" Library/Unknown | wc -l) -eq 1 ]; then
    fd -t d "$*" Old\ Library/
    if [ $(fd -t d "$*" Old\ Library/ | wc -l) -eq 1 ]; then
        found="$(find_music "$*" | head -n 1)"
        if [ -n "$found" ]; then
            source="${found#*/}"
            source="${source%%/*}"
            if [ -n "$source" ]; then
                beet modify -a "$*" source="$source"
                exit 0
            fi
        fi
    fi
fi
echo >&2 "Error finding $*"
exit 1
