#!/bin/sh
# shellcheck disable=SC2188

set -e

scriptdir="$(cd "$(dirname "$0")" && pwd -P)"

# shellcheck source=./trap.sh
. "$scriptdir/trap.sh"
# shellcheck source=./common-music.sh
. "$scriptdir/common-music.sh"

sort_playlist() {
    if grep -q '^# nosort' "$1"; then
        cat
    else
        # shellcheck disable=SC2119
        sort_tracks
    fi
}

usage() {
    cat >&2 <<END
    ${0##*/} [options] [PLAYLIST..]

    Options:
    -v   Verbose mode
END
exit 2
}

verbose=0
err_redir=/dev/null
while getopts vh opt; do
    case "$opt" in
        v)
            verbose=1
            err_redir=
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
    usage
fi

tmpdir=$(mktemp -d -t "${0##*/}.XXXX")
trap 'rm -rf "$tmpdir"' EXIT
trap 'rm -rf "$tmpdir"; trap - INT; kill -INT $$' INT
trap 'rm -rf "$tmpdir"; trap - TERM; kill -TERM $$' TERM
tmpfile="$tmpdir/playlist"
seen="$tmpdir/seen"
newfiles="$tmpdir/new"

if [ $# -gt 1 ] && [ $verbose -eq 0 ]; then
    printf >&2 "%s" "Processing playlists.."
fi
for playlist; do
    if [ $# -eq 1 ] || [ $verbose -eq 1 ]; then
        echo >&2 "Processing $playlist"
    else
        echo >&2 .
    fi

    if [ "$playlist" = "-" ]; then
        cat "$playlist" >"$tmpdir/from_playlist"
        playlist="$tmpdir/from_playlist"
    fi

    if grep -q "^# shuffle" "$playlist"; then
        shuffle=1
    else
        shuffle=
    fi

    >"$seen"
    # shellcheck disable=SC2002
    cat "$playlist" \
        | grep -v '^#' \
        | while read -r line; do
            echo "$line" >"$tmpfile"
            rockuefort list ${shuffle:+--shuffle} "$tmpfile" 2>${err_redir:-/dev/stderr} \
                | sort_playlist "$playlist" >"$newfiles"

            if grep -q '^# nodedupe' "$playlist" \
                || echo "$line" | grep -q '^album=[^|]*$'; then
                cat "$newfiles"
            else
                comm -13 "$seen" "$newfiles"
            fi
            cat "$newfiles" >>"$seen"
        done
done
if [ $# -gt 1 ] && [ $verbose -eq 0 ]; then
    echo >&2 "done"
fi
