#!/bin/sh

# shellcheck source=./common-music.sh
. "$(dirname "$0")"/common-music.sh

set -e

dap_dir="$(beet get-config-path alternatives.dap.directory)"

cd "$dap_dir" || exit 1

TAB="$(printf '\t')"
beet ls -f '$artpath'"$TAB"'$alt_dap' singleton:false \^alt_dap:/Single\ Tracks/ \^alt_dap:non-album alt_dap- \
    | grep -v "^None$TAB" \
    | sed -e 's#/[^/]*$##' \
    | uniq \
    | while IFS="$TAB" read -r artpath destdir; do
        base="${artpath##*/}"
        destname="$(echo "$base" | sed -e 's/\.[0-9]\././')"
        if [ -e "$base/$destname" ]; then
            if [ -n "$(find "$destdir" -name "$destname" -newer "$artpath")" ]; then
                continue
            fi
            convert "$artpath" -resize 220x220 -bordercolor black -border 10x10 "$destdir/$destname"
        fi
    done
