#!/bin/sh

# shellcheck source=./common-music.sh
. "$(dirname "$0")"/common-music.sh

set -e

if [ "$1" = "-f" ]; then
    rm -rf DAP/*
else
    find DAP -type l \
        | while read -r fn; do test -e "$fn" || echo "$fn"; done \
        | tr '\n' '\0' \
        | xargs -0 rm -fv \
        | sed -e 's,^,-,'
    # Ensure we remove remnants of removed albums
    find DAP -name cover.jpg -print0 | xargs -0 rm -f
fi
beet alt update dap --create
"$(dirname "$0")/update-dap-covers"

cd DAP || exit 1
# Update rockuefort playlists
rockuefort scan
"$(dirname "$0")/update-playlists"
if [ -e .git ]; then
    git add . && git commit -m "Update"
fi
