#!/bin/sh

# shellcheck source=./common-music.sh
. "$(dirname "$0")"/common-music.sh

set -e

dap_dir="$(beet get-config-path alternatives.dap.directory)"

if [ "$1" = "-f" ]; then
    rm -rf "$dap_dir"/*
else
    find "$dap_dir" -type l \
        | while read -r fn; do test -e "$fn" || echo "$fn"; done \
        | tr '\n' '\0' \
        | xargs -0 rm -fv \
        | sed -e 's,^,-,'
    # Ensure we remove remnants of removed albums
    find "$dap_dir" -name cover.jpg -print0 | xargs -0 rm -f
    rm -rf "$dap_dir"/_Playlists
fi
beet alt update dap --create
"$(dirname "$0")/update-dap-covers"

cd "$dap_dir" || exit 1
if [ -e .git ]; then
    git add . && git commit -m "Update"
fi
