#!/bin/sh
# shellcheck disable=SC2016
#
# TODO: warn if an album isn't a soundtrack, but has soundtrack, OST, or
# 'Sound Track' in the album title

# Set certain album items to singleton
beet ls -f '$id' -a last_import:1 | while read -r album_id; do
    beet modify -W -y "album_id:$album_id" singleton:false album:"non-album tracks" , singleton:false album:@ album_id= album= 2>/dev/null

    # Extract embedded album art if needed
    beet extractart -a "id:$album_id" "artpath:^"

    # Clear embedded album art. FIXME: run this only if there's embedded art
    # to clear, otherwise it pointlessly writes *all* the metadata changes
    # pending, not just the art
    # beet clearart -y "album_id:$album_id"
done

# Likely a single
beet modify -W -a last_import:1 albumtotal:1 albumtype::'^(|other)$' albumtype=single 2>/dev/null

# Save comments.txt if set
beet-export-album-comments last-import:1

# Clear out the album field for imported singletons
beet modify -W -y last_import:1 album::. album= 2>/dev/null

# 'Various Artists' albums not flagged as compilations
beet modify -W -y -a last_import:1 album_query:is_various_not_comp comp=1 2>/dev/null

beet ls -a -f '$path' last_import:1
beet ls -f '$path' last_import:1

if [ -z "$BEETS_NO_REVEAL" ]; then
    # Open the album folder
    beet open -- -a last_import:1

    # Reveal singleton files
    beet reveal last_import:1
fi
