#!/bin/sh
# shellcheck disable=SC2016

# Extract embedded album art if needed
beet extractart -a last_import:1 "artpath:^"

# Save comments.txt if set
beet-export-album-comments last_import:1


beet ls -a -f '$path' last_import:1
beet ls -f '$path' last_import:1

if [ -z "$BEETS_NO_REVEAL" ]; then
    # Open the album folder
    beet open -- -a last_import:1

    # Reveal singleton files
    beet reveal last_import:1
fi
